### ISSUE TITLE
tag list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#210] opened 2017-06-25 21:00 UTC
when you click on a tag in the media list, it just takes you to an empty page with the name of the tag on it. it should show a list of all media with that tag,

**Comment by JoeIceCream** [comment] 2017-09-10 23:04
@rohrlach I'm not sure sure if we're aware of this, but when I try to add a second avatar with the same tag as the first, the terminal prints out that that name has already been taken. Is this a bug?

**Comment by rohrlach** [comment] 2017-09-10 23:12
That's not a bug. 

It's a confirmation that the tag exists and that it's assigning the existing one rather than creating a duplicate

**Comment by JoeIceCream** [comment] 2017-09-11 00:17
@rohrlach Oh I see, however I'm still not able to assign the tag to the media. This message displays and won't let me assign the same tag. Is there another way to assign existing tags?

**Comment by rohrlach** [comment] 2017-09-11 00:24
Hm... Okay, could be a bug.

Have a look through the code and see you if can work it out 😉

**Comment by rohrlach** [comment] 2017-12-23 15:53
@alexanderglenn looks like you were the last person to commit to the Issue#210 branch, can you provide an update here?

**Comment by alexanderglenn** [comment] 2018-03-21 01:28
The tag page should now show all the media and stages that are assigned to it in a table.

**Comment by helenvarley** [comment] 2018-03-27 16:19
trying to test but the server is down or something?

**Comment by rohrlach** [comment] 2018-03-27 16:46
Sorry - Forgot to update the version of Ruby on the server.

Have incorporated this into the automatic update scipt for the QA instance and have confirmed that the server is running again.

**Comment by helenvarley** [comment] 2018-03-27 18:33
great, seems to work how one would expect it to! :)

**Closed** 2018-04-04 19:34 UTC
Labels: bug, tags
